ome/omero-ms-zarr

- README.md
- pom.xml
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForId.java
- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataService.java
- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataVerticle.java
- src/main/resources/zarr-context.xml
- src/scripts/post.py
This PR bears a simplified https://gitlab.com/openmicroscopy/incubator/omero-ms-mapr-jdbc showing how to use OMERO context to obtain user/group IDs and offer them from a JSON API over HTTP. Next steps (unordered) are plausibly:
* Bring up enough context for `PixelsService` to be used to instantiate pixel buffers.
* Based on https://github.com/jhamman/xpublish endpoints offer a Zarr-based view of pixel buffers.
* Including min-max from StatsInfo could assist napari.
* Drop the example ID-providing endpoint.
* Translate the `pom.xml` to a `build.gradle`.
> Add a small OMERO server-side microservice with RESTful API

- src/main/resources/zarr-extras.xml
Fix #10 by setting the Hibernate properties correctly so that `FullText/` is found.
> set correct FullText directory for OMERO application context

- src/scripts/omero_to_zarr.py
Creates zarr file which can be opened with napari.
Creates 'plain' Zarr (no groups)
```
$ python omero_to_zarr 123
```
This is based on @manics example, but uses a different `shape`,
based on XYZCT dimension order, shape is:
```
shape=(size_t, size_c, size_z, size_y, size_x),
```
Can open with ```napari 0.2.12``` with:
```
im = da.from_zarr('./123.zarr')
with napari.gui_qt():
viewer = napari.view_image(
im,
contrast_limits=(min, max)
```
```
$ python omero_to_zarr.py 9767678
$ rsync -rvP --progress 9767678.zarr 10.0.48.3:/uod/idr/objectstore/minio/idr/zarr/
```
IDR Images I've done this for:
- [9767678](http://idr.openmicroscopy.org/webclient/?show=image-9767678): idr0056, uint16, X: 660, Y: 501, Z: 1, T: 1, C: 3, total = 1.2 MB
- …
> Add omero_to_zarr.py

- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
This PR corrects a missed opportunity to promptly close an instantiated pixel buffer.
> Close useless pixel buffer.

- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
Fix multiscales metadata from microservice to match #17.
Should be able to continue using `fetch-ms-zarr.py` to download with,
`--endpoint_url http://localhost:8080/ --url_format '{url}image/{image}/'`
> have microservice provide multiscales value as an array

- build.gradle
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/test/java/org/openmicroscopy/ms/zarr/PixelBufferCacheTest.java
- src/test/java/org/openmicroscopy/ms/zarr/TileSizeAdjustmentTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsTestBase.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrMetadataTest.java
- src/test/java/org/openmicroscopy/ms/zarr/stub/PixelBufferFake.java
Should suffice if Travis is green. `ZarrMetadataTest` has `ZarrEndpointsTestBase` broken out as a superclass because the chunking / tiling tests for the pixel data use it too, those can follow in another PR once done. Increases the visibility of a couple of things beyond `private` to make them directly testable.
> Add unit tests for microservice.

- src/scripts/fetch-ms-zarr.py
This updates the fetch script to download files
from S3 (EBI & UoD). This is the layout that
the microservice likely will want to implement
over time. Up for discussion is certainly the
URL format (`{url}/idr/zarr/v0.1/{image}.zarr/`).
Note also that the multiscale metadata currently
differs.
cc: @mtbc
> fetch-ms-zarr: use s3 layout (spec.md v0.1)

- src/test/java/org/openmicroscopy/ms/zarr/ZarrBinaryDataTest.java
- src/test/java/org/openmicroscopy/ms/zarr/stub/PixelBufferFake.java
Adds a unit test for the pixel data encoded in the chunks returned from the microservice.
> Add unit test for binary chunks returned by microservice.

- src/scripts/rechunk.py
Permits copying an array from one Zarr store to another while applying a new chunk size. Dask `from_zarr` and `to_zarr` are used to perform this in parallel. For long running tasks, a dashboard can be activated with `--distributed` to watch the processing occur. Multiscale metadata will need to be updated for the Zarr group _after_ the fact.
> Rechunk script

- .pre-commit-config.yaml
- .travis.yml
- examples/basic-http/create-zarr.py
- examples/basic-http/explore-zarr.py
- src/scripts/fetch-ms-zarr.py
- src/scripts/omero_to_zarr.py
- src/scripts/rechunk.py
Closes https://github.com/ome/omero-ms-zarr/issues/24
To reformat Python code files after editting simply run `pre-commit run -a`.
This also splits Travis into three stages so it's easier to see whats failed.
> Autoformat with black. Add travis stages.

- README.md
- src/main/java/org/openmicroscopy/ms/zarr/Configuration.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataService.java
- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataVerticle.java
- src/test/java/org/openmicroscopy/ms/zarr/PixelBufferCacheTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsTestBase.java
Adds microservice configuration properties,
- `omero.ms.zarr.buffer-cache.size`
- `omero.ms.zarr.chunk.size.min`
- `omero.ms.zarr.compress.zlib.level`
- `omero.ms.zarr.net.path.image`
- `omero.ms.zarr.net.port`
and describes them in the [README](https://github.com/mtbc/omero-ms-zarr/blob/configuration-properties/README.md).
> Make microservice configurable.

- spec.md
This formalizes the output of webgateway/imgData for the moment
as consumed by ome-zarr-py.
cc: @manics @will-moore @mtbc @jburel
> spec: add rendering information

- Dockerfile
- src/main/java/org/openmicroscopy/ms/zarr/ConfigEnv.java
- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataService.java
This should allow the Docker image to be run using the same configuration format as the omero-web and omero-server containers.
For example, https://github.com/ome/docker-example-omero with these changes:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 60fd75c..efc64d5 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -29,6 +29,21 @@ services:
volumes:
- "omero:/OMERO"
+  omerozarr:
+    image: omero-ms-zarr
+    environment:
+      CONFIG_omero_db_host: database
+      CONFIG_omero_db_user: omero
+      CONFIG_omero_db_pass: omero
+      CONFIG_omero_db_name: omero
+      CONFIG_omero_ms_zarr_net_path_image: /idr/zarr/v0.1/{image}.zarr/
+    networks:
+      - omero
+    ports:
+      - "8080:8080"
+    volumes:
+      - "omero:/OMERO"
+
omeroweb:
image: …
```
> Optionally add CONFIG_ env-vars to properties

- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsTestBase.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrMetadataTest.java
Replaces `scale` with an initial pass at OMERO metadata. Fixes #30 and #31.
> Adjust metadata that microservice includes in .zattrs

- src/main/java/org/openmicroscopy/ms/zarr/ZarrDataVerticle.java
This PR reworks the verticle a little more to fit Vert.x conventions. Notably, if you try something disabling, like setting `omero.ms.zarr.net.port=80` but running as an unprivileged user, the log output should include a useful ERROR line. Fixes #37.
> Log the failure to start HTTP server listening.

- build.gradle
Was released last week with [various bugfixes](https://github.com/vert-x3/wiki/wiki/3.9.1-Release-Notes).
> bump to Vert.x v3.9.1

- README.md
Since the error messages for `curl http://localhost:8080/image/1234.zarr/` don't explain what the problem is add an example.
> Add note to README about testing with curl

- README.md
- build.gradle
- src/main/java/org/openmicroscopy/ms/zarr/Configuration.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/test/java/org/openmicroscopy/ms/zarr/TileSizeAdjustmentTest.java
`omero.ms.zarr.chunk.size.min` defaults to trying to have chunks include at least 1MB of data when uncompressed. This PR fixes #14 by allowing the microservice to include multiple Z planes in a chunk in reaching that minimum. Pick a multi-Z image with small X and Y and check that the resulting `.zarray` looks good for achieving that chunk size (with z > 1, middle number of "chunks" list, also note dtype) and that the image still views just fine.
In review, going separately by commit or ignoring whitespace with `w=1` may help.
> allow microservice to offer multi-Z chunks

- README.md
- build.gradle
- src/main/java/org/openmicroscopy/ms/zarr/Configuration.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
Fixes #13. Try,
```
wget -r -l0 http://localhost:8080/image/1234.zarr/
```
to fetch image 1234. (All the downloaded `index.html` can be ignored.)
Also can set `omero.ms.zarr.folder.layout=flattened` to try the non-nested layout for chunks.
> Provide HTML directory listings from microservice.

- src/main/java/org/openmicroscopy/ms/zarr/HttpHandler.java
- src/main/java/org/openmicroscopy/ms/zarr/OmeroDao.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/test/java/org/openmicroscopy/ms/zarr/PixelBufferCacheTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsTestBase.java
- src/test/java/org/openmicroscopy/ms/zarr/stub/RouteBase.java
- src/test/java/org/openmicroscopy/ms/zarr/stub/RouterFake.java
- src/test/java/org/openmicroscopy/ms/zarr/stub/RoutingContextFake.java
Previously the microservice was needlessly repeating some of Vert.x's work in matching URI patterns against corresponding behavior. This PR bears general factoring to make it easier to add further methods: the masks work is building on this branch. There should be no outward changes in behavior.
> Internal refactoring of microservice dispatch.

- spec.md
see also:
- https://github.com/IDR/idr-zarr-tools
> First version of mask metadata

- README.md
- src/main/java/org/openmicroscopy/ms/zarr/Configuration.java
- src/main/java/org/openmicroscopy/ms/zarr/OmeroDao.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
- src/main/java/org/openmicroscopy/ms/zarr/mask/Bitmask.java
- src/main/java/org/openmicroscopy/ms/zarr/mask/ImageMask.java
- src/main/java/org/openmicroscopy/ms/zarr/mask/UnionMask.java
- src/scripts/copy-masks.py
- src/scripts/overlapping-masks.py
- src/test/java/org/openmicroscopy/ms/zarr/ZarrBinaryDataTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrBinaryImageTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrBinaryMaskTest.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsImageTestBase.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrEndpointsTestBase.java
- src/test/java/org/openmicroscopy/ms/zarr/ZarrMetadataTest.java
- src/test/java/org/openmicroscopy/ms/zarr/mask/TestUnionMasks.java
For a split view, within the main image directory, this PR offers a `masks/` folder with subfolders named for the ROI IDs because masks within the same ROI are combined into one. If the ROIs do not overlap then `masks/labeled/` is also offered, the "pixel values" being the ROI IDs for this initial version.
As with the main image Zarr, the masks can also be fetched via `wget -r -l0` though one might afterward want to run, `find . -name index.html -exec rm {} +`. Mask endpoints should respect the setting for `omero.ms.zarr.folder.layout`.
Although the code should perform reasonably already, clarity is not much sacrificed in that pursuit. In moving nearer production, various operations could be optimized: for example, the DAO could directly offer the most appropriate query, more …
> initial provision of masks by microservice

- spec.md
Captures the changes to the spec for turning labeled images into multiscale arrays. Depending on the decisions around color etc. (see https://github.com/ome/omero-ms-zarr/issues/62#issuecomment-676062914) this may include a top-level "label" key.
see https://github.com/ome/ome-zarr-py/pull/45
> Labeled multiscales

- spec.md
Follows on from #70 with the color specification. Comments from https://github.com/ome/omero-ms-zarr/pull/70#pullrequestreview-482185225 may need re-reviewing.
> Write up new image-label proposal

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- src/main/java/org/openmicroscopy/ms/zarr/Configuration.java
- src/main/java/org/openmicroscopy/ms/zarr/RequestHandlerForImage.java
Swaps the default of `omero.ms.zarr.folder.layout` property and changes the version to `0.2`.
> 0.2: use nested folders by default

- README.md
- build.gradle
This PR allows to exclude the S3 tests if minio is not running
This PR will fail until https://github.com/ome/omero-ms-zarr/pull/91 is merged
> Exclude test
